#!/bin/sh

if [ "$#" -ne 2 ]; then
    echo "freeze [on/off] '<msg>'"
    exit 1
fi

if [ "$1" = "on" ]; then
    if [ $(curl -s localhost:8080/githook) -eq 1 ];
        then echo "already frozen"
    else
        curl -s --data-urlencode "msg=${2}" localhost:8080/freeze -o /dev/null
        echo "build frozen"
    fi
elif [ "$1" = "off" ]; then
    if [ $(curl -s localhost:8080/githook) -eq 0 ];
        then echo "already unfrozen"
    else
        curl -s --data-urlencode "msg=${2}" localhost:8080/unfreeze -o /dev/null
        echo "build unfrozen"
    fi
else
    echo "freeze [on/off] '<msg>'"
    exit 1
fi
